// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    district_demand_detail: {
        name: "district_demand_detail";
        parameters: {
          /** STRING - use sql.string() */
          state: SQLStringMarker;
          /** STRING - use sql.string() */
          district: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          district_name: string;
          /** @sqlType STRING */
          state: string;
          /** @sqlType DOUBLE */
          demand_score: number;
          /** @sqlType BIGINT */
          population: number;
          /** @sqlType STRING */
          demand_quality_label: string;
          /** @sqlType INT */
          usable_indicator_count: number;
          /** @sqlType INT */
          low_sample_indicator_count: number;
          /** @sqlType INT */
          suppressed_indicator_count: number;
        }>;
      };
    district_evidence: {
        name: "district_evidence";
        parameters: {
          /** STRING - use sql.string() */
          specialty: SQLStringMarker;
          /** STRING - use sql.string() */
          state: SQLStringMarker;
          /** STRING - use sql.string() */
          district: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          district_name: string;
          /** @sqlType STRING */
          state: string;
          /** @sqlType STRING */
          specialty: string;
          /** @sqlType STRING */
          facility_id: string;
          /** @sqlType STRING */
          facility_name: string;
          /** @sqlType STRING */
          facility_type: string;
          /** @sqlType STRING */
          city: string;
          /** @sqlType STRING */
          pin_code: string;
          /** @sqlType DOUBLE */
          latitude: number;
          /** @sqlType DOUBLE */
          longitude: number;
          /** @sqlType STRING */
          source_url: string;
          /** @sqlType STRING */
          claim_id: string;
          /** @sqlType STRING */
          source_field: string;
          /** @sqlType STRING */
          claim_text: string;
        }>;
      };
    district_scores: {
        name: "district_scores";
        parameters: {
          /** STRING - use sql.string() */
          specialty: SQLStringMarker;
          /** STRING - use sql.string() */
          state: SQLStringMarker;
          /** STRING - use sql.string() */
          verdict: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          district_name: string;
          /** @sqlType STRING */
          state: string;
          /** @sqlType STRING */
          specialty: string;
          /** @sqlType DOUBLE */
          demand_score: number;
          /** @sqlType DOUBLE */
          raw_demand_score: number;
          /** @sqlType STRING */
          demand_label: string;
          /** @sqlType STRING */
          demand_evidence_label: string;
          /** @sqlType INT */
          n_facilities: number;
          /** @sqlType INT */
          k_facilities: number;
          /** @sqlType INT */
          claim_count: number;
          /** @sqlType DOUBLE */
          documented_supply_rate: number;
          /** @sqlType DOUBLE */
          wilson_lo: number;
          /** @sqlType DOUBLE */
          wilson_hi: number;
          /** @sqlType DOUBLE */
          gap_score: number;
          /** @sqlType STRING */
          confidence_label: string;
          /** @sqlType STRING */
          verdict_label: string;
        }>;
      };
    saved_scenarios: {
        name: "saved_scenarios";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          scenario_id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          created_by: string;
          /** @sqlType TIMESTAMP */
          created_at: string;
          /** @sqlType TIMESTAMP */
          updated_at: string;
          /** @sqlType STRING */
          specialty: string;
          /** @sqlType STRING */
          geo_filter_json: string;
          /** @sqlType STRING */
          notes: string;
        }>;
      };
    specialties: {
        name: "specialties";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          specialty: string;
          /** @sqlType STRING */
          display_name: string;
          /** @sqlType INT */
          facility_count: number;
        }>;
      };
    states: {
        name: "states";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          state: string;
        }>;
      };
  }
}
